import { StyleSheet } from 'react-native';

export const colors = {
  oceanBlue: '#1e3a8a',
  lightBlue: '#3b82f6',
  deepBlue: '#0f172a',
  golden: '#fbbf24',
  darkGolden: '#d97706',
  yellow: '#fde047',
  darkYellow: '#eab308',
  white: '#ffffff',
  black: '#000000',
  gray: '#6b7280',
  darkGray: '#374151',
};

export const commonStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.oceanBlue,
  },
  backgroundGradient: {
    flex: 1,
    backgroundColor: colors.deepBlue,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 15,
  },
  backButton: {
    width: 40,
    height: 40,
    borderRadius: 20,
    backgroundColor: colors.yellow,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 15,
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: colors.yellow,
    textTransform: 'uppercase',
    fontFamily: 'CrimsonText-Regular',
  },
  titleContainer: {
    alignItems: 'center',
    marginVertical: 30,
    paddingHorizontal: 20,
  },
  gameTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: colors.golden,
    textAlign: 'center',
    textTransform: 'uppercase',
    marginBottom: 10,
    fontFamily: 'CrimsonText-Regular',
  },
  goldenFrame: {
    borderWidth: 3,
    borderColor: colors.golden,
    borderRadius: 10,
    padding: 15,
    backgroundColor: 'rgba(251, 191, 36, 0.1)',
  },
  button: {
    backgroundColor: colors.golden,
    paddingVertical: 15,
    paddingHorizontal: 30,
    borderRadius: 25,
    marginVertical: 10,
    alignItems: 'center',
    minWidth: 200,
  },
  buttonText: {
    color: colors.black,
    fontSize: 22,
    fontWeight: 'bold',
    textTransform: 'uppercase',
    fontFamily: 'CrimsonText-Regular',
  },
  secondaryButton: {
    backgroundColor: colors.yellow,
    paddingVertical: 12,
    paddingHorizontal: 25,
    borderRadius: 20,
    marginVertical: 5,
    alignItems: 'center',
  },
  secondaryButtonText: {
    color: colors.black,
    fontSize: 22,
    fontWeight: '600',
    fontFamily: 'CrimsonText-Regular',
  },
  storyCard: {
    backgroundColor: colors.deepBlue,
    borderWidth: 2,
    borderColor: colors.yellow,
    borderRadius: 15,
    padding: 20,
    margin: 15,
  },
  storyTitle: {
    fontSize: 22,
    fontWeight: 'bold',
    color: colors.deepBlue,
    marginBottom: 10,
    textAlign: 'center',
    fontFamily: 'CrimsonText-Regular',
  },
  storyDescription: {
    fontSize: 22,
    color: colors.deepBlue,
    lineHeight: 28,
    textAlign: 'center',
    fontFamily: 'CrimsonText-Regular',
  },
  questionCard: {
    backgroundColor: colors.golden,
    borderRadius: 15,
    padding: 20,
    margin: 15,
    alignItems: 'center',
  },
  questionText: {
    fontSize: 22,
    fontWeight: 'bold',
    color: colors.black,
    textAlign: 'center',
    marginBottom: 20,
    fontFamily: 'CrimsonText-Regular',
  },
  optionButton: {
    backgroundColor: colors.golden,
    paddingVertical: 15,
    paddingHorizontal: 20,
    borderRadius: 20,
    marginVertical: 8,
    width: '90%',
    alignItems: 'center',
  },
  optionText: {
    color: colors.black,
    fontSize: 22,
    fontWeight: '600',
    textAlign: 'center',
    fontFamily: 'CrimsonText-Regular',
  },
  feedbackCard: {
    backgroundColor: colors.golden,
    borderRadius: 15,
    padding: 20,
    margin: 15,
    alignItems: 'center',
  },
  feedbackText: {
    fontSize: 22,
    fontWeight: 'bold',
    color: colors.black,
    textAlign: 'center',
    marginBottom: 20,
    fontFamily: 'CrimsonText-Regular',
  },
  navigationButtons: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingHorizontal: 20,
    paddingVertical: 15,
  },
  navButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: colors.yellow,
    justifyContent: 'center',
    alignItems: 'center',
  },
  emptyStateContainer: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  emptyStateText: {
    fontSize: 22,
    color: colors.yellow,
    textAlign: 'center',
    marginBottom: 30,
    fontWeight: 'bold',
    fontFamily: 'CrimsonText-Regular',
  },
  bottomNavigation: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    paddingHorizontal: 20,
    paddingVertical: 10,
    // backgroundColor: 'rgba(59, 130, 246, 0.8)',
  },
  bottomNavButton: {
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: colors.yellow,
    justifyContent: 'center',
    alignItems: 'center',
  },
});
